# Generated by Django 5.1.7 on 2025-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('previous_quantity', models.IntegerField(editable=False)),
                ('new_quantity', models.IntegerField(editable=False)),
                ('reason', models.CharField(choices=[('restock', 'Restock'), ('damage', 'Damage/Loss'), ('correction', 'Quantity Correction'), ('transfer', 'Warehouse Transfer')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
